subgraphs:
  socket-service:
    routing_url: http://localhost:4001/graphql
    schema:
      subgraph_url: http://localhost:4001/graphql
#  api:
#    routing_url: http://localhost:8000/graphql
#    schema:
#      subgraph_url: http://localhost:8000/graphql
